add_newline = false

[directory]
format = "[:$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
# truncation_prefix = ".../"
style = "bold blue"

[username]
format = "[$user]($style)"
style_user = "green"
show_always = true

[hostname]
format = "[@$hostname]($style)"
style = "green"
# ssh_only = false

[line_break]
disabled = true

[python]
format = "[${pyenv_prefix}(\\($virtualenv\\))]($style) "

[nodejs]
disabled = true

[rust]
disabled = true

[package]
format = "[- $symbol$version]($style) "

[git_branch]
format = "[$symbol$branch ]($style)"
